const productos = [{
    id: 1,
    nombre: 'Bart',
    precio: 120,
    img: src = "img/bart.jpeg",
    cantidad: 1,
  },
  {
    id: 2,
    nombre: 'Fire',
    precio: 150,
    img: src = "img/fuego.png",
    cantidad: 1,
  },
  {
    id: 3,
    nombre: 'Kurt',
    precio: 150,
    img: src = "img/kurt.jpeg",
    cantidad: 1,
  },
  {
    id: 4,
    nombre: 'DC',
    precio: 250,
    img: src = "img/rainbow.png",
    cantidad: 1,
  },
  {
    id: 5,
    nombre: 'Joker',
    precio: 150,
    img: src = "img/joker.jpg",
    cantidad: 1,
  },
];